version: "3.7"

services:
  # Backend API
  facerecognitionbrain-api:
    container_name: backend
    # image: node:12.13.1
    build: ./
    command: npm start
    working_dir: /usr/src/facerecognitionbrain-api
    environment:
      POSTGRES_USER: leandro
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    # links:
    #  - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/facerecognitionbrain-api
      # Postgres
  postgres:
    # container_name: postgres
    environment:
      # POSTGRES_URI: postgres://leandro:1234@postgres:5432/smart-brain
      POSTGRES_USER: leandro
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    image: postgres
    ports:
      - "5432:5432"
